### ISSUE TITLE
Centre elements on all pages and leave margin/padding on left and right

### ISSUE THREAD

**Issue by syan-syan** [datagovsg/avenue#12]
<img width="1422" alt="Screenshot 2021-01-27 at 12 04 24 PM" src="https://user-images.githubusercontent.com/55272802/105941200-d97b5980-6097-11eb-9c3b-02a5ba512d4c.png">

Enhances readability, so that eyes dont have to travel madly from left to right just to get through a post

Can check Reddit's breakpoints as guideline

**Comment by Buooy** [comment]
I think this should be done
