### ISSUE TITLE
Sort news feed by 'Top' (Popular) or 'New' (Recent)

### ISSUE THREAD

**Issue by syan-syan** [datagovsg/avenue#4]
Add button options to sort the news feed by 'Top' (Popular) or 'New' (Recent)

example from reddit
<img width="678" alt="Screenshot 2021-01-27 at 9 10 51 AM" src="https://user-images.githubusercontent.com/55272802/105927771-a036ef80-607f-11eb-86b8-0fd9e7dec7a7.png">

**Comment by Buooy** [comment]
can get a designer to design this better. for now its in the navbar
